name: GitLab

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Git
        run: |
          git config --global user.email "kx.yang.apply@outlook.com"
          git config --global user.name "kxyang"
      - name: Fetch and Rebase from GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git remote add gitlab https://oauth2:${GITLAB_TOKEN}@gitlab.com/bob4043209/bob-plugin-vocabulary.com.git
          git fetch gitlab main
          git rebase gitlab/main
      - name: Push to GitLab
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git push gitlab main:main
